# Generated by Django 2.1 on 2018-08-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
    ]
