# Generated by Django 2.1 on 2018-08-06 01:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
