# Generated by Django 2.1 on 2018-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20180806_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
