# Generated by Django 2.1 on 2018-08-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_conversation_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
