# Generated by Django 2.1 on 2018-08-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_conversation_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp']},
        ),
    ]
