# Generated by Django 2.1 on 2018-08-06 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20180806_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(related_name='receiver_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
