# Generated by Django 2.1 on 2018-08-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20180806_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receivers',
        ),
    ]
