# Generated by Django 2.1 on 2018-08-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20180806_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='unread_count',
            new_name='my_unread_count',
        ),
        migrations.AddField(
            model_name='conversation',
            name='their_unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
