# Generated by Django 2.1 on 2018-08-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20180818_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
